### ISSUE TITLE
Clarify CFP process around status, feature maturity

### ISSUE THREAD

**Issue by joestringer** [cilium/design-cfps#24]
It is useful to understand the status of CFPs as they make their way into this repository, so that stakeholders involved in the discussions are aligned around the degree of agreement on various aspects of each CFP. 

Part of solving this issue would be to draw up a process that describes the expectations regarding "merged" CFPs, perhaps at multiple levels such as alpha, beta, etc. We can likely draw inspiration from Kubernetes upstream, Gateway API, and others to inform best practices here.

Questions that this process should solve:
- What does it mean if a CFP is merged into this repository?
- How does an author iterate on a CFP if there is uncertainty or the implementation details impact the design over time?
- How does an author drive a feature towards becoming a generally available / stable feature?

**Comment by xmulligan** [comment]
Seems similar to https://github.com/cilium/design-cfps/issues/4. Happy to close that in favor of this one though

**Comment by joestringer** [comment]
Ah yes, I think you're right @xmulligan . I think it's useful to ensure that the questions above are also solved, but I'm happy to close this / merge the ideas into that issue.
