### ISSUE TITLE
Add DCO checker on PRs

### ISSUE THREAD

**Issue by joestringer** [cilium/design-cfps#25]
It doesn't look like we have any bot to ensure the Developer's Certificate of Origin is signed on commits. It would be good to set this up.

**Comment by hacktivist123** [comment]
This has been implemented @joestringer and @xmulligan 

see this PR: https://github.com/cilium/design-cfps/pull/27/checks

**Comment by joestringer** [comment]
Awesome, thanks!

**Comment by joestringer** [comment]
Hi @hacktivist123 , the DCO doesn't seem to be showing up. For instance on this PR, there is a commit without signoff. I don't see any check at the bottom of the PR about this. https://github.com/cilium/design-cfps/pull/32

**Comment by hacktivist123** [comment]
hey @joestringer i'm not sure why it doesn't show at the bottom however there is a check showing 
<img width="733" alt="Screenshot 2024-06-05 at 22 28 39" src="https://github.com/cilium/design-cfps/assets/26572907/327278a3-cd4a-442e-bf13-d129e75a9af8">

**Comment by hacktivist123** [comment]
there is also a check on this PR

<img width="733" alt="Screenshot 2024-06-05 at 22 28 39" src="https://github.com/cilium/design-cfps/assets/26572907/bc514d76-2528-4e58-b2b5-125b6123e322">

**Comment by hacktivist123** [comment]
There is also a check on this PR 

<img width="1080" alt="Screenshot 2024-06-05 at 22 32 02" src="https://github.com/cilium/design-cfps/assets/26572907/f4818e29-13c3-40d8-a51c-4cf0dc4b331b">

**Comment by joestringer** [comment]
Hmm. I'm not familiar with this DCO app since we use a different mechanism in cilium/cilium. However, I don't think that the above check will block PRs, so it'll still be very easy to merge commits without signoff.

I can't tell if something is wrong with the way GitHub is handling this, and it's temporary, or there's something wrong with the DCO app. In the settings for this repo, I can't configure the DCO workflow as required in order to merge PRs.

**Comment by hacktivist123** [comment]
Most likely something wrong with the app, it was working before I think. I'll take a look at how is done in Cilium/Cilium and replace this app

**Comment by joestringer** [comment]
It would be _nice_ if that app could just work.. I think that the way we do it in cilium/cilium is more complicated and relies on a custom bot. But if that's what we need to make it work, then I'm alright with it.

The reason I bring this up is that we may want to roll out a similar mechanism across various repos within the cilium organization, so if we can "just" install the app to get this functionality then that would be the easiest path to enable it in different repos.

**Comment by hacktivist123** [comment]
You have a good point, I’ll investigate this issue tomorrow and see what can be done. I’ll share my feedback/findings tomorrow with you.

**Comment by joestringer** [comment]
DCO seems to be showing up in all the right places now. I think we can close this issue.
